language: node_js
node_js:
    - "5.1"

cache:
    directories:
        - node_modules

before_install:
    - curl -s -o ~/push-to-dashboard.sh https://hookr.enrise.com/client.sh && chmod +x ~/push-to-dashboard.sh
    - [ "$TRAVIS_PULL_REQUEST" = "false" ] && ~/push-to-dashboard.sh "Basic $HOOKR_AUTH_KEY" "CIMonitor" "CIMonitor" "$TRAVIS_BRANCH" "test" "started" "#$TRAVIS_JOB_NUMBER"

script:
    - sleep 30s;
    
after_success:
    - [ "$TRAVIS_PULL_REQUEST" = "false" ] && ~/push-to-dashboard.sh "Basic $HOOKR_AUTH_KEY" "CIMonitor" "CIMonitor" "$TRAVIS_BRANCH" "test" "success" "#$TRAVIS_JOB_NUMBER"
    
after_failure:
    - [ "$TRAVIS_PULL_REQUEST" = "false" ] && ~/push-to-dashboard.sh "Basic $HOOKR_AUTH_KEY" "CIMonitor" "CIMonitor" "$TRAVIS_BRANCH" "test" "failure" "#$TRAVIS_JOB_NUMBER"
