language: node_js
node_js:
    - "10"

cache: yarn

script:
    - make test

notifications:
    webhooks:
        urls:
            - secure: "Cr/TzZYISLX2A1CvYc2XJ4TdiDs8vz/a9u4ZsWppEMxRim/eb7WAUh9dHTlVzaPw9nYbmo+mzRumfWj/O5csMiU/aoAqhvAncn8x0QGcBvvsIRNAEII8bpwX338CeN8gdnRHWVW/B1Sgkc9MEJsSOo78Jl9mNHMYF7ATr7AHz00xph6iPvI9tKw2/MMp72HQsauZz81sxAq2xL1hOJsfe6amgK8BbiS6aMqR5z+1jEZ7vDFVa992wc37TmJzIiWquCikBn7aZTRR9HNOe8Ae9EOyTZPj+e3yTv48CNNvH6TsEC20zrQrSUaZSqSSB6wiuaRfYyoBJ061xHDRcDeNWKlvauphwIu36aefUxVl7AeYKfNUZRV+eXfTVNKR8QT9TX/VLvXzoKrsOeLQ4fIQ4auQhihuWpVeIIwau+eXTVEWSmA5M6vE5tS38Cyqr8BJwpDzBB2ZRtmxtqA1o7JNzdVEdYcGZGkq3gFecZehTdkB0CzItbI000SPzEjAr2iuZM6tLQO6g9TOX0d0Cgfx6Vskfja2BmKLW6kWOIQeYYZ02s7KcGBsEgCizaxbVbgO/UmciNl3zbo/A0glps+ucrvV+bugynH3RJD2cBYaM9QspIEe87e1SnJ/Gjt1DerjhfK/xKHZa33qtjLZaCDzjJRx0ryPhPhwk+7MP1QNEwk="
        on_success: always
        on_failure: always
        on_start: always
        on_cancel: always
        on_error: always
