language: node_js
node_js:
    - "10"

cache: yarn

script:
    - make test

notifications:
    webhooks:
        urls:
            - secure: "HQS8wEXDTyjI0DZiLbSuSz9TOnYnFtXPr79t6dSMZfosfcZwbJP4tFZktfC60vMJ8rgOdCr3NWLz1KAW6hFE1/xmNlhsE43n9MaUXoms+dnYRG0X+MmfszzUOpa01+Kw2LRCHh3RJV6Rq/k40zlpk+EVJXt4Ik/uztUgojOQOj/VSduGncI+kkm48IVnBwPPXPDRjQcuRovtnYPRfOIyW7HSnJJikgxnj+axldnK9F768D4Ik+udjCw8R7TY+Qn1GXWn20hQ+auUshGQTbTjZgOf753cR5D57wM5lMnYxfKZSKxrAhaJLqxqNhBSjBemL5h0B0YWOOUffJeEef0lsHL3ycRkmoxxY7wMRR7SL1Vt0aCMylK3waiFCM9wUwlw23R+7QsNuCxTuAXLZuQPhX27eGwLkggffgwtg7lJPh8oObMQiFCQB/rQh18syR5cGEZE5el+hLoxbS4NK+Q123kL7GF2fuUy6q2Vx9wjVqBV7Z0QlOYYMGz0f0Up/JlwFAhprZRX4gyefgYsXXifeLNkqjmren6fVc3K8KfucYnOCH5kFN5OpFZq4pYG3/vSeQJ1/Ph0JyeeGIB45LSSlaNK43T/f+loxIaGermAbDMe2/MpjeT7kd/AAHUL//iBP1Bskx3nHpz68vXpFrFLLH3CI4oPMBmsgmefe0TIn7U="
        on_success: always
        on_failure: always
        on_start: always
        on_cancel: always
        on_error: always
