language: node_js
node_js:
    - "5.1"

cache:
    directories:
        - node_modules

before_install:
    - curl -O ~/push-to-dashboard.sh https://hookr.enrise.com/client.sh && chmod +x ~/push-to-dashboard.sh
    - ~/push-to-dashboard.sh "$HOOKR_AUTH_KEY" "CIMonitor" "CIMonitor" "$TRAVIS_BRANCH" "test" "started" "#$TRAVIS_BUILD_ID"

script:
    - sleep 30s;
    
after_success:
    - ~/push-to-dashboard.sh "$HOOKR_AUTH_KEY" "CIMonitor" "CIMonitor" "$TRAVIS_BRANCH" "test" "success" "#$TRAVIS_BUILD_ID"
    
after_failure:
    - ~/push-to-dashboard.sh "$HOOKR_AUTH_KEY" "CIMonitor" "CIMonitor" "$TRAVIS_BRANCH" "test" "failure" "#$TRAVIS_BUILD_ID"
