language: node_js
node_js:
    - "5.1"

cache:
    directories:
        - node_modules

before_install:
    - curl -s -o ~/hookr.sh https://hookr.enrise.com/clients/travis.sh && chmod +x ~/hookr.sh
    - ~/hookr.sh "CIMonitor" "CIMonitor" "started"

script:
    - node_modules/.bin/gulp eslint-fail-on-error
    
after_success:
    - ~/hookr.sh "CIMonitor" "CIMonitor" "success"
    
after_failure:
    - ~/hookr.sh "CIMonitor" "CIMonitor" "failure"
