site_name: CIMonitor
theme: readthedocs
repo_url: https://github.com/CIMonitor/CIMonitor
site_author: Rick van der Staaij
nav:
    - Home: index.md
    - Setup:
          - Setup CIMonitor: setup/CIMonitor.md
          - Setup Raspberry: setup/raspberry.md
    - Status API: status-API.md
    - Connecting services:
          - GitLab: services/GitLab.md
          - Travis CI: services/Travis-CI.md
    - Modules:
          - Dashboard video: modules/dashboard-video.md
          - Hue light: modules/hue-light.md
          - Led strip: modules/led-strip.md
          - Marble run: modules/marble-run.md
          - Power up: modules/power-up.md
          - Traffic light: modules/traffic-light.md
    - Server slave: server-slave.md
