site_name: CIMonitor
theme: readthedocs
repo_url: https://github.com/CIMonitor/CIMonitor
site_author: Rick van der Staaij
dev_addr: 0.0.0.0:9998
pages:
    - Home: index.md
    - Getting started:
          - Setup CIMonitor: setup/CIMonitor.md
          - Configuration: setup/configuration.md
          - Run a service: setup/run-as-service.md
          - Setup Raspberry: setup/Raspberry.md
    - Status API: status-API.md
    - Link a service:
          - GitLab: services/GitLab.md
          - Travis CI: services/Travis-CI.md
    - Modules:
          - Dashboard video: modules/dashboard-video.md
          - Hue light: modules/hue-light.md
          - Led strip: modules/led-strip.md
          - Marble run: modules/marble-run.md
          - Power up: modules/power-up.md
          - Traffic light: modules/traffic-light.md
    - Server slave: server-slave.md
